# .github/auto-assign.yml
addReviewers: true
addAssignees: false

# Включаем режим групп — берём по 1 из каждой
useReviewGroups: true

# Список групп (имена команд без @org/)
reviewGroups:
  middle:
    - frontend-middle
  junior:
    - frontend-junior

# Опционально: не назначать автора PR, если он в команде
skipUsers:
  - ${{ github.actor }}