ddReviewers: true
addAssignees: false

reviewers:
  groups:
    middle:
      - frontend-middle
    junior:
      - frontend-junior

useReviewGroups: true
numberOfReviewers: 0 

skipReviewer:
  - ${{ github.actor }}
